# Use the official Node.js image as the base image
FROM node:14

# Set the working directory to the app directory
WORKDIR /usr/src/app

# Copy the shared package.json and package-lock.json to the working directory
COPY package*.json ./


# Install app dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

EXPOSE 3030

# Command to run the application
CMD ["nx", "serve", "auth"]
